version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=batch
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "80:80"
    volumes:
      - /sessions
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root

