spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/batch
    username: root
    password: root
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
    properties.hibernate.dialect.storage_engine: innodb
    hibernate.ddl-auto: validate